Pong-Arcade/ft_transcendence

frontend/src/components/ui/boards/Board.tsx
frontend/src/components/ui/boards/ScrollBarBoard.tsx
frontend/src/components/ui/buttons/Button.tsx
frontend/src/components/ui/chat/ChatElement.tsx
frontend/src/components/ui/chat/ChatInput.tsx
frontend/src/components/ui/chat/ChatList.tsx
frontend/src/components/ui/lists/List.tsx
frontend/src/components/ui/lists/ListElement.tsx
frontend/src/index.tsx
frontend/src/pages/Chat/index.tsx
frontend/src/pages/Lobby/LobbyLeftBoard.tsx
frontend/src/pages/Lobby/LobbyRightBoard.tsx
frontend/src/pages/Login/index.tsx
frontend/src/pages/Rank/index.tsx
frontend/src/styles/GlobalStyle.ts
frontend/src/styles/styled.d.ts
frontend/src/styles/theme.ts

Rank page 추가 및 전반적인 UI 개선 (UI의 경우, 다른 자료들을 참고하여 지속적으로 개선할 예정)
https://user-images.githubusercontent.com/74703501/213126879-a07fd016-ccee-4efa-aacd-833fca9136b8.mov

Fe/dev/improve UI/#3

---

.gitignore
backend/.gitignore
backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/config/configuration.ts
backend/src/config/typeorm.config.ts
dev.docker-compose.yaml
docker-compose.yaml

DB 연동 초기 설정을 완료했습니다.
backend 디렉토리와 postgres 디렉토리에 노션(env 페이지)에 명세한 env 파일을 넣어야 동작합니다!

[BE] DB 연결 초기 설정 추가 #16

---

frontend/src/components/atoms/Button/Button.tsx
frontend/src/components/atoms/CheckBox/CheckBox.tsx
frontend/src/components/atoms/Input/Input.tsx
frontend/src/components/modules/ContentList/ContentList.tsx
frontend/src/components/modules/CreateRoomModal/CreateRoomModal.tsx
frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
frontend/src/components/modules/ModalContent/ModalContent.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
frontend/src/hooks/useCreateRoomForm.tsx
frontend/src/utils/createRoomFormValidate.tsx

방을 생성할 때 form으로 제출할지, 소켓이벤트로 처리할지 안 정해졌지만 입력 내용을 가져와야 하는 것은 동일하기 때문에 그 부분을 처리했습니다.
close #30

Fe/dev/feat submit form/#30

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/atoms/Avatar/Avatar.tsx
frontend/src/components/atoms/Button/Button.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
package-lock.json

유저 프로필 정보창에서 이미지를 클릭하면 upload 창이 뜨도록 했습니다.
아직 api 호출 테스트를 해보지는 않아서 작동은 하지 않습니다.
close #7

[FE] FEAT: image resize/#7

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/atoms/Avatar/Avatar.tsx
package-lock.json

아바타 이미지 클릭시 파일 업로드 창 띄움.
이미지 업로드시 파일 해상도 조정

[fe]FEAT: 아바타 리사이즈 #7

---

backend/package-lock.json
backend/package.json
backend/src/auth/42/ft.strategy.ts
backend/src/auth/42/mock.strategy.ts
backend/src/auth/auth.controller.ts
backend/src/auth/session/session.serializer.ts
backend/src/dto/chatroom.list.dto.ts
backend/src/dto/ft.user.dto.ts
backend/src/dto/gameroom.list.dto.ts
backend/src/dto/match.history.dto.ts
backend/src/dto/rank.dto.ts
backend/src/dto/response/chatroom.list.response.dto.ts
backend/src/dto/response/chatroom.users.info.response.dto.ts
backend/src/dto/response/gameroom.list.response.dto.ts
backend/src/dto/response/gameroom.users.info.response.dto.ts
backend/src/dto/response/online.users.response.dto.ts
backend/src/dto/response/rank.list.response.dto.ts
backend/src/dto/response/user.block.list.response.dto.ts
backend/src/dto/response/user.friend.list.response.dto.ts
backend/src/dto/response/user.info.response.dto.ts
backend/src/dto/response/user.recent.match.history.response.dto.ts
backend/src/dto/user.chat.dto.ts
backend/src/dto/user.dto.ts
backend/src/dto/user.status.dto.ts
backend/src/enum/chatroom.mode.enum.ts
backend/src/enum/gameroom.status.enum.ts
backend/src/enum/match.result.enum.ts
backend/src/enum/user.chat.mode.enum.ts
backend/src/enum/user.status.enum.ts
backend/src/user/user.controller.ts

서버측에서 사용할 DTO를 추가했습니다.
이중에서 API 응답을 저장하는 DTO는 response라는 디렉토리에 추가했습니다.
response용 DTO는 노션에 명세한 것과 동일합니다.

[BE] 서버측에서 사용할 DTO 추가 #34

---

frontend/src/components/atoms/RankingFilter/RankingFilter.tsx
frontend/src/components/atoms/RankingFilter/index.tsx
frontend/src/pages/Ranking.tsx

랭킹 페이지에 필터 버튼을 추가했습니다.
close #38

[FE] FEAT: 랭킹 페이지 필터 버튼 추가 #38

---

frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/api/auth.ts
frontend/src/api/axios.ts
frontend/src/components/atoms/Avatar/Avatar.tsx
frontend/src/components/atoms/Modal/Modal.tsx
frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
frontend/src/components/modules/LoginButton/LoginButton.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
frontend/src/components/modules/UserInfoSettingModal/index.tsx
frontend/src/hooks/useInfoSetting.tsx
frontend/src/hooks/useUserInfo.tsx
frontend/src/pages/Lobby.tsx
frontend/src/utils/axios.ts
frontend/tsconfig.json
package-lock.json

로그인 후 첫 로그인인 경우 프로필 설정이 뜨도록 했습니다.
내정보에서 프로필설정 버튼을 누르면 프로필 설정이 뜨도록 했습니다.
close #35

[FE] 프로필 수정 기능 추가(사진, 닉네임) /#35

---

frontend/src/api/auth.ts
frontend/src/components/atoms/List/List.tsx
frontend/src/components/atoms/ListItem/ListItem.tsx
frontend/src/components/modules/ChatRoomButtons/ChatRoomButtons.tsx
frontend/src/components/modules/ChatRoomButtons/index.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/ChatRoomUserList/index.tsx
frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
frontend/src/components/modules/InviteModal/InviteModal.tsx
frontend/src/components/modules/InviteModal/index.tsx
frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
frontend/src/components/modules/LoginButton/LoginButton.tsx
frontend/src/components/modules/PaginationList/PaginationList.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
frontend/src/hooks/useInfoSetting.tsx
frontend/src/pages/ChatRoom.tsx
frontend/src/pages/Lobby.tsx

[FE] FEAT: 채팅방 초대 기능 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/api/auth.ts
frontend/src/api/axios.ts
frontend/src/components/modules/ChooseGameModal/ChooseGameModal.tsx
frontend/src/components/modules/LobbyCreateRoomButtons/LobbyCreateRoomButtons.tsx
frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
frontend/src/components/modules/LoginButton/LoginButton.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
frontend/src/hooks/useCreateGameModal.tsx
frontend/src/hooks/useCreateRoom.tsx
frontend/src/hooks/useFirstLoginModal.tsx
frontend/src/hooks/useQuickGameModal.tsx
frontend/src/index.tsx
frontend/src/pages/Lobby.tsx
frontend/src/pages/Root.tsx
frontend/src/state/LoadingState.tsx

[FE] REFACTOR: 코드 정리 #51

---

frontend/src/components/modules/Chat/Chat.tsx
frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
frontend/src/components/modules/LobbyCreateRoomButtons/LobbyCreateRoomButtons.tsx
frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
frontend/src/index.tsx
frontend/src/pages/Lobby.tsx
frontend/src/pages/Root.tsx
frontend/src/utils/ChatSocket.tsx

소켓에 대해서 주석 처리를 했습니다.
규칙을 정하고 따르기란 어렵지만, 최대한 컨벤션을 따라 주시면 감사하겠습니다.
dev 브랜치에는 dev.docker-compose.yaml로 실행 시켰을 시 에러가 안 나는 코드만 pr 올려주시기 바랍니다.

[FE] REFACTOR: 프론트 소켓 주석처리

---

backend/src/dto/match.history.dto.ts
backend/src/entity/ladder.stat.entity.ts
backend/src/entity/match.history.entity.ts
backend/src/entity/normal.stat.entity.ts
backend/src/enum/match.type.enum.ts
postgres/pong_arcade.sql

match_history, normal_stat, ladder_stat 테이블과 entity를 추가했습니다.
match_history에는 대전 유형(LADDER, NORMAL)을 나타내는 MatchType을 저장합니다.

[BE] match_history, normal_stat, ladder_stat 테이블 추가

---

backend/src/stat/stat.controller.ts
backend/src/user/user.controller.ts
frontend/src/api/ranking.ts
frontend/src/components/modules/ChatRoomInvitePagination/ChatRoomInvitePagination.tsx
frontend/src/components/modules/ChatRoomInviteUserItem/ChatRoomInviteUserItem.tsx
frontend/src/components/modules/ChatRoomUserListPagination/ChatRoomUserListPagination.tsx
frontend/src/components/modules/InviteModal/InviteModal.tsx
frontend/src/components/modules/LobbyChatRoomPagination/LobbyChatRoomPagination.tsx
frontend/src/components/modules/LobbyGameRoomPagination/LobbyGameRoomPagination.tsx
frontend/src/components/modules/LobbyUserListPagination/LobbyUserListPagination.tsx
frontend/src/components/modules/Pagination/Pagination.tsx
frontend/src/components/modules/RankingItem/RankingItem.tsx
frontend/src/components/modules/RankingItem/index.tsx
frontend/src/components/modules/RankingPagination/RankingPagination.tsx
frontend/src/hooks/useLobbyUserList.tsx
frontend/src/hooks/useRankList.tsx
frontend/src/pages/Ranking.tsx

[FE] Ranking api 및 디자인 구현 #76

---

backend/src/dto/request/chatroom.create.request.dto.ts
backend/src/dto/request/gameroom.create.request.dto.ts
backend/src/dto/response/gameroom.users.info.response.dto.ts
backend/src/enum/gameroom.mode.enum.ts

- #81 에 따라 Request용 DTO를 추가했습니다.
- `ChatRoomUsersInfoResponseDto` -> `GameRoomUsersInfoResponseDto` 클래스 명 오타가 있어 수정했습니다.
- 금일 회의 결과에 따라 게임방도 채팅방과 마찬가지로 PRIVATE, PROTECTED가 생겼으므로 `GameRoomMode`를 추가했습니다.

[BE] Request DTO 추가

---

frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
frontend/src/components/modules/ModalTitle/ModalTitle.tsx
frontend/src/components/modules/QuickGameModal/QuickGameModal.tsx
frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
frontend/src/pages/GameRoom.tsx
frontend/src/styles/GlobalStyle.ts

X 모양이 있는 모달창의 경우 esc 키를 누르면 닫히게 했습니다.

[FE] 모달창 esc 기능 추가

---

backend/src/auth/repository/auth.repository.ts
backend/src/dto/user.dto.ts
backend/src/entity/user.entity.ts
postgres/pong_arcade.sql

user 테이블에 최초 로그인 시간인 `first_login` 필드를 추가했습니다.
유저가 처음 로그인할 때, 로그인한 시간으로 저장되도록 `addUserIfNotExists` 함수를 수정했습니다.

[BE] user에서 최초 로그인 정보 추가

---

backend/src/auth/auth.controller.ts
backend/src/mock/mock.repository.ts
backend/src/relation/block.controller.ts
backend/src/relation/friends.controller.ts
backend/src/user/user.controller.ts
frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
frontend/src/components/modules/Pagination/Pagination.tsx

mock server를 사용하지 못하는 관계로 mock data 로직을 수정했습니다.
백앤드 분들은 확인 후 이상 여부 댓글로 부탁드립니다.
이후에도 이런 식으로 작업을 하려고 합니다.
이상이 있다면 다음부터는 그 부분을 개선하도록 하겠습니다.
close #98

[BE] FEAT: user && relation mock data logic #98

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chat.module.ts
backend/src/chat/chat.service.ts
backend/src/chat/chatroom.controller.ts
backend/src/chat/chatroom.entity.ts
backend/src/dto/request/chatroom.change.info.request.dto.ts
backend/src/user/user.module.ts
backend/src/user/user.service.ts

chat API Controller 부분을 작성 완료했습니다.
EventEmitter로 ChatGateway에 있는 함수에 이벤트를 발생시켜 해당 함수에서 로직(다른 유저에게 소켓 이벤트 발생, 서버측에 저장된 채팅방 객체 CRUD)을 처리하도록 했습니다.

[BE] chat API 구현

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chatroom.entity.ts
backend/src/mock/mock.repository.ts
backend/src/status/status.entity.ts
frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
frontend/src/index.tsx
frontend/src/pages/Lobby.tsx
frontend/src/utils/ChatSocket.tsx

[COMMON] FEAT: 로비 온라인 유저 목록 갱신

---

backend/src/chat/chat.geteway.ts
frontend/src/components/modules/Chat/Chat.tsx
frontend/src/components/modules/LobbyUserItem/LobbyUserItem.tsx
frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
frontend/src/pages/Lobby.tsx
frontend/src/utils/ChatSocket.tsx

소켓 버퍼 크기 제한으로 발생하던 에러를 해결하고, 컨벤션에 맞지 않는 변수 명들을 수정하였습니다.

[COMMON] FIX: 소켓 버퍼 문제 해결

---

frontend/src/api/room.ts
frontend/src/components/atoms/Typography/Typography.tsx
frontend/src/components/modules/ButtonGroup/ButtonGroup.tsx
frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
frontend/src/components/modules/ErrorModal/ErrorModal.tsx
frontend/src/components/modules/GameTypeCheckBoxGroup/GameTypeCheckBoxGroup.tsx
frontend/src/components/modules/GameTypeCheckBoxGroup/index.tsx
frontend/src/components/modules/LabledInput/LabledInput.tsx
frontend/src/hooks/useChatRoomForm.tsx
frontend/src/hooks/useGameRoomForm.tsx
frontend/src/hooks/useLobbyData.tsx
frontend/src/hooks/useModifyChatRoomForm.tsx
frontend/src/pages/GameRoom.tsx

게임방에서 상태는  대기 / 준비 입니다.
이미지는 게임방의 유저에 대한 정보를 얻어오면 추가하도록 하겠습니다.
close #103

[FE] 게임방 생성 && 게임방 디자인 변경 #103

---

backend/src/chat/chat.geteway.ts
frontend/src/components/modules/Chat/Chat.tsx

[COMMON] RENAME: 컨벤션에 맞지 않는 변수명 수정

---

backend/src/chat/chat.geteway.ts
frontend/src/components/atoms/ChatList/ChatList.tsx
frontend/src/components/modules/Chat/Chat.tsx
frontend/src/index.tsx
frontend/src/pages/Lobby.tsx
frontend/src/utils/ChatSocket.tsx

차단한 유저의 메시지가 출력되지 않도록 하는 기능을 추가했습니다.

[FE] FEAT: 차단한 유저의 메시지 무시 #119

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/dto/request/update.user.info.request.dto.ts
backend/src/user/repository/user.repository.interface.ts
backend/src/user/repository/user.repository.ts
backend/src/user/user.controller.ts
backend/src/user/user.module.ts
backend/src/user/user.service.ts
package-lock.json
package.json

유저의 nickname 혹은 아바타 이미지를 변경하는 API를 구현했습니다.
아바타 이미지는 파일을 업로드하여 서버측의 정적 파일로 저장하도록 구현했습니다.
/uploads라는 디렉토리에 저장이 되며, 외부에서 접근할 때는 /static/{이미지.jpg} 형태로 접근할 수 있습니다.

[BE] 유저정보 변경 API 구현

---

frontend/src/components/modules/Chat/Chat.tsx
frontend/src/index.tsx
frontend/src/pages/Lobby.tsx
frontend/src/utils/ChatSocket.tsx

ChatSocket을 context로 만들어서 Provider에서 제공하도록 변경했습니다.

[FE]REFACTOR: ChatSocket을 전역에서 사용할 수 있도록 변경

---

frontend/src/components/atoms/ChatList/ChatList.tsx
frontend/src/components/modules/Chat/Chat.tsx
frontend/src/components/modules/ChatInput/ChatInput.tsx
frontend/src/components/modules/ChatInput/index.tsx

채팅입력, 새로운 메시지 추가마다 chat component가 렌더링 되던 것을 개선.

[FE] REFACTOR: chat refactor #121

---

backend/src/auth/auth.module.ts
backend/src/auth/repository/auth.repository.ts
backend/src/stat/repository/stat.repository.ts

[BE] FIX: stat API 관련 버그 수정 #132

---

frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
frontend/src/components/modules/Pagination/Pagination.tsx
frontend/src/components/modules/RelationConfirmModal/RelationConfirmModal.tsx
frontend/src/components/modules/StatList/StatList.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
frontend/src/hooks/useBlockUsers.tsx
frontend/src/hooks/useFriendUsers.tsx
frontend/src/hooks/useRelation.tsx

gFe/dev/feat stat sample data and design/#136

---

backend/src/auth/auth.controller.ts
backend/src/chat/chatroom.controller.ts
backend/src/game/gameroom.controller.ts
backend/src/stat/stat.controller.ts

[BE] FEAT: Controller에 UseGuards, ApiBearerAuth 추가 #134

---

frontend/src/api/axios.ts
frontend/src/api/ranking.ts
frontend/src/api/room.ts
frontend/src/components/modules/ChatRoomUserListPagination/ChatRoomUserListPagination.tsx
frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
frontend/src/components/modules/ErrorModal/ErrorModal.tsx
frontend/src/components/modules/LobbyChatRoomItem/LobbyChatRoomItem.tsx
frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
frontend/src/components/modules/LobbyChatRoomPagination/LobbyChatRoomPagination.tsx
frontend/src/components/modules/LobbyUserListPagination/LobbyUserListPagination.tsx
frontend/src/components/modules/ModifyChatRoomModal/ModifyChatRoomModal.tsx
frontend/src/hooks/useLobbyData.tsx

[FE] FEAT: 채팅방 입장 승인 거부 처리 #143

---

frontend/src/api/room.ts
frontend/src/components/modules/Chat/Chat.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/ChatRoomUserListPagination/ChatRoomUserListPagination.tsx
frontend/src/components/modules/LobbyUserListPagination/LobbyUserListPagination.tsx
frontend/src/hooks/useLobbyData.tsx
frontend/src/pages/Lobby.tsx
frontend/src/state/SocketState.tsx
frontend/src/utils/ChatSocket.tsx
postgres/pong_arcade.sql

채팅방 안에서의 기능과 일부 event의 기능을 개선했습니다.

[COMMON] [FEAT] chat event 추가구현 및 개선

---

frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx

[FE] REFACTOR: 메뉴바 귓속말 삭제

---

frontend/src/components/modules/ChatInviteModal/ChatInviteModal.tsx
frontend/src/components/modules/ChatInviteModal/index.tsx
frontend/src/pages/Lobby.tsx

[FE] FEAT: 채팅방 초대 모달 추가

---

backend/src/app.module.ts
backend/src/chat/chat.module.ts
backend/src/dto/response/user.detail.response.dto.ts
backend/src/enum/user.status.enum.ts
backend/src/stat/stat.module.ts
backend/src/stat/stat.service.ts
backend/src/user/user.controller.ts
backend/src/user/user.module.ts
backend/src/user/user.service.ts

[BE] FEAT: User Detail Info Response 수정

---

backend/src/chat/chat.service.ts
backend/src/chat/chatroom.controller.ts
backend/src/dto/response/chatroom.create.users.info.response.dto.ts
backend/src/dto/response/chatroom.users.info.response.dto.ts
frontend/src/api/room.ts
frontend/src/components/modules/ChatRoomItem/ChatRoomItem.tsx
frontend/src/components/modules/ChatRoomPasswordModal/ChatRoomPasswordModal.tsx
frontend/src/components/modules/ChatRoomPasswordModal/index.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
frontend/src/components/modules/LobbyChatRoomItem/LobbyChatRoomItem.tsx
frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
frontend/src/components/modules/Pagination/Pagination.tsx
frontend/src/pages/ChatRoom.tsx

[FE] FEAT: 채팅방 비밀번호 입력 모달 추가 #161

---

backend/src/game/game.gateway.ts
backend/src/game/gameroom.controller.ts
backend/src/game/gameroom.service.ts
frontend/src/api/room.ts
frontend/src/components/modules/ChooseGameModal/ChooseGameModal.tsx
frontend/src/components/modules/LobbyCreateRoomButtonGroup/LobbyCreateRoomButtonGroup.tsx
frontend/src/components/modules/Pagination/Pagination.tsx
frontend/src/components/modules/QuickGameModal/QuickGameModal.tsx
frontend/src/event/GameEvent/lobbyGameEvent.ts
frontend/src/hooks/useLobbyData.tsx
frontend/src/pages/Lobby.tsx

아직 에러가 나는 부분이 있어서 수요일에 수정하고 머지하는 것이 좋을 거 같습니다
close #166

[FE] FEAT: quick match 게임 기능 추가 #166

---

backend/src/user/repository/user.repository.interface.ts
backend/src/user/repository/user.repository.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts

전체 온라인 유저 정보 API에서 오프라인 유저 정보도 함께 가져와지는 버그를 수정했습니다.

[BE] 전체 온라인 유저 정보 API 버그 수정

---

backend/src/dto/game.user.status.dto.ts
backend/src/dto/response/gameroom.users.info.response.dto.ts
backend/src/game/game.gateway.ts
backend/src/game/gameroom.service.ts
frontend/src/components/modules/ChatInviteModal/ChatInviteModal.tsx
frontend/src/components/modules/ChatRoomInvitePagination/ChatRoomInvitePagination.tsx
frontend/src/components/modules/InviteModal/InviteModal.tsx
frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
frontend/src/components/modules/Pagination/Pagination.tsx
frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
frontend/src/event/GameEvent/gameRoomEvent.ts
frontend/src/pages/GameRoom.tsx

[FE] FEAT: 유저 상세 정보 반영 #176

---

backend/src/chat/chat.geteway.ts
frontend/src/components/atoms/ChatList/ChatList.tsx
frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/event/ChatEvent/lobbyChatEvent.ts
frontend/src/hooks/useLobbyData.tsx
frontend/src/index.tsx
frontend/src/pages/ChatRoom.tsx
frontend/src/pages/Lobby.tsx

채팅방 정보 변경시 채팅방 참여 유저에게도 업데이트
socket event off 해주던 것을 useEffect의 return 으로 변경.
useLobbyData에 있던 채팅방 리스트 event를 lobbyChatEvent로 이동

[FE] REFACTOR: 소켓 이벤트 리팩토링

---

backend/src/auth/auth.controller.ts
backend/src/game/game.gateway.ts
backend/src/game/gameroom.controller.ts
backend/src/game/gameroom.service.ts
frontend/src/api/room.ts
frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/InviteGameModal/InviteGameModal.tsx
frontend/src/components/modules/InviteGameModal/index.tsx
frontend/src/components/modules/InviteGameWaitingModal/InviteGameWaitingModal.tsx
frontend/src/components/modules/InviteGameWaitingModal/index.tsx
frontend/src/components/modules/InviteRejectModal/InviteRejectModal.tsx
frontend/src/components/modules/InviteRejectModal/index.tsx
frontend/src/components/modules/ModalTitle/ModalTitle.tsx
frontend/src/event/GameEvent/chatRoomGameEvent.ts

[FE] 채팅방에서 게임 초대 기능 추가 #167

---

backend/src/auth/repository/auth.repository.ts

유저 생성 시, 아래 과정을 트랜잭션으로 묶어서 관리하도록 수정했습니다.
- user 테이블 insert
- two_factor_auth 테이블 insert
- normal_stat 테이블 insert
- ladder_stat 테이블 insert
2차 인증 시, 인증 코드는 서버에서 발행하는 것이고, 인증을 할 때 마다 변경되는 값이므로 암호화하는 것이 의미가 없다고 판단되어 암호화하지 않았습니다.
마찬가지로 채팅방 비밀번호 정보도 DB에 저장하는 것이 아닌 메모리에 저장되는 값이므로 따로 암호화하지 않았습니다.

[BE] FIX: 유저 생성 시, 트랜잭션 관리

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chat.service.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts
frontend/src/hooks/useLobbyData.tsx

온라인 유저 목록을 받아오는 API에서 DB에 접근하지 않고 서버에서 들고 있던 users를 이용하도록 변경.
채팅방 목록에 lobby 방이 출력 되지 않도록 함.
온라인 유저 목록에서 억까 당할 수 있는 부분 개선.

[COMMON] REFACTOR: 온라인 유저 api 개선, 억까방지 코드추가

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chat.service.ts
backend/src/chat/chatroom.controller.ts
backend/src/chat/chatroom.entity.ts
backend/src/game/game.gateway.ts
frontend/src/components/modules/ChatConfirmModal/ChatConfirmModal.tsx
frontend/src/components/modules/ChatInviteModal/ChatInviteModal.tsx
frontend/src/components/modules/ChatRoomPasswordModal/ChatRoomPasswordModal.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
frontend/src/hooks/useLobbyData.tsx
frontend/src/index.tsx
frontend/src/pages/ChatRoom.tsx
frontend/src/pages/Lobby.tsx

초대받은 유저만 private 모드 채팅방에 입장할 수 있도록 api 조건 추가
chatroom entity의 Room 클래스 id 변수를 roomId로 변경 (프론트와 호환을 위함)
chatRoomState에 입장해있는 roomId를 업데이트 하도록 추가.
채팅방에 비정상적인 접속시 에러 출력

[COMMON] FEAT: 채팅방 PRIVATE 모드 구현, 구조 개선

---

backend/src/game/game.gateway.ts
backend/src/game/gameConfig.json
frontend/src/api/room.ts
frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
frontend/src/components/modules/FailModal/FailModal.tsx
frontend/src/components/modules/GameBoard/GameBoard.tsx
frontend/src/components/modules/GameFinish/GameFinish.tsx
frontend/src/components/modules/GameFinish/index.tsx
frontend/src/components/modules/ModalTitle/ModalTitle.tsx
frontend/src/event/GameEvent/gameBoardEvent.ts
frontend/src/event/GameEvent/gameStartEvent.ts
frontend/src/hooks/useGameRoomForm.tsx
frontend/src/hooks/useLobbyData.tsx
frontend/src/index.tsx
frontend/src/pages/GameRoom.tsx

아직 미흡한 부분이 많을 거라 생각됩니다
디자인은 일요일에 클러스터 컴퓨터에 맞출 생각입니다.
1. 게임 대기 중
2. 게임 종료
지금까지 발견한 오류로는 2가지가 있습니다.
1. 방장이 게임방 나가기 api를 호출하지 않고 브라우저를 닫았을 경우 게임방이 사라지지 않는 오류
2. 게임 끝나면 유저의 게임 유저의 레디 상태가 변경되지 않는 오류
close #168

[COMMON] frontend backend 게임 기능 연결 #168

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chatroom.controller.ts
backend/src/game/game.gateway.ts
backend/src/relation/friends.service.ts
backend/src/user/user.controller.ts
frontend/src/api/room.ts
frontend/src/api/users.ts
frontend/src/components/modules/ChatConfirmModal/ChatConfirmModal.tsx
frontend/src/components/modules/ChatInviteModal/ChatInviteModal.tsx
frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
frontend/src/components/modules/GameFinish/GameFinish.tsx
frontend/src/components/modules/InviteConfirmModal/InviteConfirmModal.tsx
frontend/src/components/modules/InviteModal/InviteModal.tsx
frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
frontend/src/components/modules/LobbyCreateRoomButtonGroup/LobbyCreateRoomButtonGroup.tsx
frontend/src/components/templates/LobbyTemplate/LobbyTemplate.tsx
frontend/src/event/ChatEvent/lobbyChatEvent.ts
frontend/src/event/GameEvent/gameBoardEvent.ts
frontend/src/hooks/useLobbyData.tsx
frontend/src/hooks/useModal.tsx
frontend/src/index.tsx
frontend/src/pages/Lobby.tsx

ajax 요청 시 로딩 페이지에서 대기 후 응답이 왔을 때 본래 페이지를 띄우도록 했습니다.

[FE] FEAT: ajax 응답 대기 시 로딩 추가 #170

---

backend/src/game/gameInstance.ts

기존 직사각형 공에서 원 모양 공으로 변경에 따른 충돌 알고리즘 변경 및 충돌 반정 로직 버그 수정

[BE] FIX: 공 모양에 따른 충돌 알고리즘 수정 #189

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chat.service.ts

> 채팅 방 생성 시, 생성자가 보이지 않는 버그를 수정했으며 약간의 리팩토링 진행했습니다

[BE] FIX: 채팅방 생성 시 유저가 보이지 않는 문제 수정

---

backend/src/chat/chat.geteway.ts
frontend/src/pages/ChatRoom.tsx
frontend/src/pages/Lobby.tsx

기존 접속자가 다른 세션으로 접속시 기존 접속 끊고 에러모달 출력해주도록 소켓 이벤트를 추가했습니다.

[COMMON] FEAT: 기존 접속자가 다른 세션으로 접속시 기존 접속 끊고 에러모달 출력 #187

---

backend/package-lock.json
backend/package.json
backend/src/auth/repository/auth.repository.ts
backend/src/dto/request/update.user.info.request.dto.ts
backend/src/entity/user.entity.ts
postgres/pong_arcade.sql

> 유저의 이름이 이미 존재할 때, 중복된 이름을 Insert하며 생기는 쿼리 에러를 방지합니다.
> 기존 DB의 수정도 일어나기 때문에 볼륨을 제거하고 다시 생성해야 정상적으로 동작합니다.

[BE] FIX: 중복된 유저 닉네임에 의한 버그 수정

---

frontend/src/components/modules/ChatRoomButtonGroup/ChatRoomButtonGroup.tsx
frontend/src/components/modules/GameBoard/GameBoard.tsx
frontend/src/components/modules/GlobalErrorModal/GlobalErrorModal.tsx
frontend/src/components/modules/InviteModal/InviteModal.tsx
frontend/src/components/modules/ModifyChatRoomModal/ModifyChatRoomModal.tsx
frontend/src/components/modules/Pagination/Pagination.tsx
frontend/src/event/GameEvent/lobbyGameEvent.ts
frontend/src/hooks/useGameRoomForm.tsx
frontend/src/hooks/useLobbyData.tsx
frontend/src/pages/ChatRoom.tsx
frontend/src/pages/GameRoom.tsx
frontend/src/pages/Lobby.tsx
frontend/src/state/ChatRoomState.ts

[FE] REFACTOR: 리팩토링

---

backend/src/game/game.gateway.ts
frontend/src/components/atoms/GameChatList/GameChatList.tsx
frontend/src/components/atoms/GameChatList/index.tsx
frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
frontend/src/components/modules/GameBoard/GameBoard.tsx
frontend/src/components/modules/GameChat/index.tsx
frontend/src/components/modules/GameFinish/GameFinish.tsx
frontend/src/components/modules/GameInput/index.tsx
frontend/src/components/modules/InviteGameModal/InviteGameModal.tsx
frontend/src/hooks/useFirstLoginModal.tsx
frontend/src/pages/GameRoom.tsx

[FE] 게임 결과 모달 디자인 수정

---

backend/src/chat/chat.geteway.ts
frontend/src/api/axios.ts

시스템 메시지가 정상적으로 출력되도록 변경.
비동기로 처리하면 안되는 소켓 이벤트들 async 삭제
존재하지 않는 user나 room에 접근 시 서버 터지는 현상 막음

[BE] 여러가지 리팩토링, 픽스

---

backend/src/chat/chat.geteway.ts
frontend/src/components/modules/ChatRoomItem/ChatRoomItem.tsx
frontend/src/pages/ChatRoom.tsx

[FE] FEAT: 채팅방 방장 표시 추가

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chatroom.controller.ts

64자 이상 채팅 전송시 막음
방 생성시 가끔 방장의 아바타가 2개 출력되던 현상 수정

[BE] FIX: 긴 채팅 막음, 가끔 방 생성시 아바타 2개 표시되던 현상 수정

---

backend/src/chat/chat.geteway.ts
backend/src/chat/chat.module.ts
backend/src/game/game.gateway.ts
frontend/src/event/GameEvent/gameRoomEvent.ts
frontend/src/event/GameEvent/lobbyGameEvent.ts
frontend/src/pages/ChatRoom.tsx
frontend/src/state/GameSocket.ts
frontend/src/utils/ChatSocket.tsx

[COMMON] 소켓 인증 기능 추가 #216

---

backend/src/chat/chatroom.controller.ts

> 방장에게 강퇴당한 사람을 초대할 수 있는 권한 부여
> 입장 권한이 없는 초대가 전송되지 않도록 수정했습니다.

[BE] FEAT: 방장에게 강퇴당한 유저를 초대할 수 있는 권한 추가

---

backend/src/game/game.gateway.ts
backend/src/game/gameroom.controller.ts
backend/src/game/gameroom.service.ts
frontend/src/components/atoms/GameChatList/GameChatList.tsx

게임방에서 외부와 귓속말이 안 되는데, 귓속말을 채팅 소켓을 사용함으로써 해결했습니다.

[BE] 귓속말 관련 버그 제거

---

backend/src/game/game.gateway.ts
backend/src/game/gameroom.controller.ts
backend/src/game/gameroom.service.ts

1. 채팅방에서 게임 초대해서 게임방 들어갔을 시 채팅 안 되는 경우
2. 게임방에서 관전자 또는 블루유저가 나갔을 시 로비 채팅이 안 되는 경우
3. 로비에서 게임방 생성 후 방장이 나갔을 때 관전자와 게임유저 채팅이 안 되는 경우
close #225

[BE] 게임방 관련 버그 제거

---

backend/src/chat/chat.geteway.ts

> 관리자가 채팅방 재입장 시, 다른 유저의 정보와 동기화되지않는 문제 수정

[BE] FIX: admin_rejoin

---

frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx

관리자가 마스터 상대로 채팅금지, 강퇴 메뉴가 뜨지 않도록 변경

[FE] FIX: 관리자가 마스터 상대로 채팅금지, 강퇴 메뉴가 뜨지 않도록 변경

---

backend/src/chat/chat.geteway.ts
frontend/src/api/room.ts
frontend/src/components/modules/ChatConfirmModal/ChatConfirmModal.tsx
frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx

> 채팅 금지 해제 버튼을 눌러도 아무 일도 일어나지 않는 버그
> /chat-rooms/unmute/:room_id/:target_user_id 로 target_user_id의 채팅 금지를 해제합니다.
> FE의 채팅금지해제 버튼을 눌렀을때 정상적으로 API 호출이 이루어지고있지 않습니다.

[BE] FIX: Unmute

---

frontend/src/components/modules/ChatRoomItem/ChatRoomItem.tsx
frontend/src/components/modules/GlobalErrorModal/GlobalErrorModal.tsx
frontend/src/hooks/useFriendUsers.tsx
frontend/src/hooks/useStatList.tsx
frontend/src/pages/ChatRoom.tsx
frontend/src/pages/GameRoom.tsx
frontend/src/pages/Lobby.tsx
frontend/src/state/ErrorState.ts
frontend/src/state/GameSocket.ts
nginx/Dockerfile

[FE] 에러 모달 떴을 시 로비로 이동 || 현재 페이지에 남기 || 로그인 페이지로 이동으로 구분

---

backend/src/game/game.gateway.ts

[BE] FIX: 게임방에서 새로고침 시, 서버 죽는 문제 수정

---

backend/src/chat/chat.geteway.ts
backend/src/game/game.gateway.ts

> 채팅 방 새로고침 시, 방이 제대로 터지지 않는 문제 수정
> 소켓 Disconnection 로직을 간단히 수정해 문제가 발생할 수 있는 부분을 줄였습니다.

[BE] 채팅방 방장 새로고침 시, 퇴장 동작이 제대로 이루어지지 않는 문제 수정

---

backend/src/chat/chat.geteway.ts
backend/src/game/game.gateway.ts

[BE] FIX: 채팅방의 글자 제한에 사용자 이름이 포함되는 버그
